### PR TITLE
Convert into a hybrid cjs/esm package

### PR DESCRIPTION
**Pull request by aurelien-reeves**
# Description

Attempt to convert into a hybrid esm/cjs package

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
(sc)css modules are tricky to manage.
Also testing the cjs build requires to put a lot of test data into the build. Not sure it is really a good thing

**Comment by aurelien-reeves** [comment]
@davidjgoss I am a bit stuck here.
There are issues using css modules with ts-node esm loader.

Would you have any idea how to move-on with this?

**Comment by davidjgoss** [comment]
@aurelien-reeves I'll certainly take a look over the weekend! This is topical for me because I need to add loaders support in cucumber-js. From what I know about ESM loaders (not much yet), I think we'll probably need to use (or write?) a loader specifically for dealing with scss files rather than that being in ts-node remit.

**Comment by aurelien-reeves** [comment]
@davidjgoss Yeap, I have written a loader for testing purpose. Then I faced other issues.

Maybe it could be interesting to pair on this actually. Any chance that it would be possible?

**Comment by davidjgoss** [comment]
@aurelien-reeves that would be good, I’ll try and find some time to block out this week and let you know

**Comment by aurelien-reeves** [comment]
I'll push my loader experiment to avoid trashing it

**Comment by aurelien-reeves** [comment]
It seems to go further, but we lost the capacity to parse tsx code :(

**Comment by davidjgoss** [comment]
Closing this as I think we can go straight to ESM only, bundlers will handle it.

**Pull request closed without merging**
