### PR TITLE
upgrade to react 18, storybook -> ladle

### PR DESCRIPTION
**Pull request by davidjgoss**
### 🤔 What's changed?

- Upgrade to React 18, change code and dependencies appropriately
- Remove Storybook and use Ladle instead, since the former seemed to struggle with React 18 and we've been wanting to move away from it for a while anyway

### ⚡️ What's your motivation? 

We want to keep current with React's major version.

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)

### ♻️ Anything particular you want feedback on?

I've had to temporarily disable the build of the Ladle app from the test workflow because the production build (it's Vite and Rollup under the hood) errors on elasticlunr, which has some invalid code that doesn't pass strict mode, and is also now unmaintained. The original lunr.js has both the same issues too. I'm exploring switching to https://github.com/LyraSearch/lyra  and will raise a follow-up PR with either that or a hack to work around the elasticlunr issue.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by mpkorstanje** [comment]
> I've had to temporarily disable the build of the Ladle app from the test workflow because the production build 

Does this imply that after merging the project is not releasable?

**Review by mpkorstanje — APPROVED** [review]
Previous remark aside, this looks like a fairly standaard upgrade to me.

**Comment by davidjgoss** [comment]
> Does this imply that after merging the project is not releasable?

No - sorry, I wasn't very clear there. It stops the production bundle working on the Ladle (nee Storybook) project, but we weren't doing anything with that yet anyway. The npm package we release and use in the HTML formatter is unaffected.

**Comment by mpkorstanje** [comment]
I believe Matt and Aslak are on holidays, more or less, this week.

**Pull request merged**
